module.exports.NOTIFICATION_STATUS = {
    JOINING_INVITATION:"INVITATION_FOR_JOINING ", 
    EVENT_CREATION : "EVENT_CREATION",
    EVENT_NOTIFICATION : "EVENT_NOTIFICATION",
    PLAN_PURCHASED : "PLAN_PURCHASED",
    PLAN_EXPIRY : "PLAN_EXPIRY",
  };
  

  